language: java

sudo: false
      
jdk:  
  - openjdk11

install:
  - mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn package -Dmaven.javadoc.skip=true -B

